# --- ОБЩИЕ НАСТРОЙКИ ---
url = "ВАША_ССЫЛКА_НА_ФОРМУ"
department = "ВАШ_ОТДЕЛ"
employee_name = "ВАШЕ_ИМЯ"

# --- НАСТРОЙКИ БРАУЗЕРА ---
# browser_mode: "local" (локальный запуск) или "remote" (удаленный через browserless.io)
browser_mode = "local"
# Токен для авторизации на browserless.io
browserless_token = "ВАШ_ТОКЕН_BROWSERLESS"
# Адрес подключения к browserless.io. По умолчанию используется глобальный балансировщик.
browserless_endpoint = "wss://chrome.browserless.io"
# Записывать сессию для просмотра в дашборде browserless.io (требует платного плана)
session_replay = false

[workload]
# --- НАСТРОЙКИ ТРУДОЗАТРАТ (в сумме должно быть ровно 100) ---
# Мои трудозатраты
SITES_ADMIN = 0         # Администрирование сайтов
SITES_DEVELOPMENT = 0   # Доработка сайтов support
REPORTING = 0           # Ведение (подготовка) отчетности
DOCUMENTATION = 0       # Работа с внутренней документацией и базой знаний
SITES_TECH_SUPPORT = 0  # Тех. сопровождение сайтов

# Остальное
BUGS_PROCESSING = 0      # Обработка багов и заявок на доработку
CLIENT_SUPPORT = 0       # Техподдержка клиентов
INTERNAL_SUPPORT = 0     # Техподдержка внутренних пользователей
WORKAROUNDS = 0          # Поиск обходных решений
INFRASTRUCTURE = 0      # Поддержка внутренней инфраструктуры (прод, препрод, разработка, тестирование)
BACKUPS = 0             # Работа с резервными копиями
INTERNAL_TRAINING = 0   # Внутреннее обучение других сотрудников
EXTERNAL_TRAINING = 0   # Обучение, повышение квалификации
ANALYTICS = 0           # Аналитика (Naumen)
TASK_TRACKER = 0        # Актуализиция информации по тикетам, работа в таск трекере (Youtrack
QUALITY_CONTROL = 0     # Контроль качества (аудит) информации
MANAGEMENT = 0          # Менеджмент (в т.ч. внутри подразделения, бизнес-процессы, смежные подразделения,
CRM_DEVELOPMENT = 0     # Доработка системы CRM
NAUMEN_ADMIN = 0        # Администрирование Naumen
